import bcrypt from "bcryptjs";

const data = {
  products: [
    {
      name: "T-Shirt",
      slug: "t-shirt",
      category: "Shirts",
      image: "/images/shirt.jpg",
      price: 49,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 11,
      countInStock: 25,
      description: "Comfortable T-Shirt",
      isFeatured: false,
    },
    {
      name: "Sweatpants",
      slug: "sweatpants",
      category: "Bottoms",
      image: "/images/sweatpant.jpg",
      price: 72,
      brand: "Champion",
      rating: 3.1,
      numReviews: 5,
      countInStock: 15,
      description: "Warm and cozy sweatpants",
      isFeatured: true,
    },
    {
      name: "Hoodie",
      slug: "hoodie",
      category: "Sweatshirts",
      image: "/images/hoodie.jpg",
      price: 125,
      brand: "Nike",
      rating: 4.9,
      numReviews: 25,
      countInStock: 25,
      description: "Stylish and warm hoodie",
      isFeatured: false,
    },
    {
      name: "Dress",
      slug: "dress",
      category: "Dresses",
      image: "/images/dress.jpg",
      price: 189,
      brand: "Zara",
      rating: 4.7,
      numReviews: 18,
      countInStock: 13,
      description: "Elegant and comfortable dress",
      isFeatured: true,
    },
    {
      name: "Jeans",
      slug: "jeans",
      category: "Bottoms",
      image: "/images/jeans.jpg",
      price: 112,
      brand: "Levi's",
      rating: 4.9,
      numReviews: 25,
      countInStock: 28,
      description: "Classic and durable jeans",
      isFeatured: false,
    },
  ],

  users: [
    { name: "admin", email: "admin@example.com", password: bcrypt.hashSync("1234"), isAdmin: true },
    { name: "user", email: "user@example.com", password: bcrypt.hashSync("1234"), isAdmin: false },
  ],
};

export default data;
